# Generated by Django 4.0 on 2022-04-30 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookweb', '0002_customuser_address_customuser_age_customuser_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('subject', models.CharField(max_length=70)),
                ('query', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='static')),
                ('author', models.CharField(max_length=100)),
                ('publishing_house', models.CharField(max_length=100)),
                ('ISBN_number', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookweb.customuser')),
            ],
        ),
    ]
