# Generated by Django 4.0 on 2022-04-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookweb', '0004_book_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='No description available', max_length=1000),
        ),
    ]
